### PR TITLE
feature: updating lock body scroll util file

### PR DESCRIPTION
**Pull request by jxrin**
**What kind of change does this PR introduce?** (check at least one)

- [ ] Bugfix (non-breaking change which fixes an issue)
- [ ] Feature (non-breaking change which adds functionality)
- [ ] Code style update
- [x] Refactor (refactoring or adding test which isn't a fix or add a feature)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Build-related changes
- [ ] Other, please describe:

**Does this PR introduce a breaking change?** (check one)

- [ ] Yes
- [x] No

**Did you test your solution?**

- [x] I lightly tested it in one browser
- [ ] I deeply tested it in several browsers
- [ ] I wrote tests around it (unit tests, integration tests, E2E tests)

## Problem Description

Update lock body scroll util file using a css variable.

## Solution Description

Updated and cleaned up the lock body scroll util file to instead lock and unlock using a global css variable.

## Side Effects, Risks, Impact

- [x] N/A

**Aditional comments:**

### CODE REVIEW

**Review by DonghyukJacobJang — CHANGES_REQUESTED** [review]
This util is not only handling scroll locking/unlocking but also restore scroll position. Please re-consider its functionality and update it accordingly.

**Comment by jxrin** [comment]
sorry about that! I'll update it accordingly to also store the lock position, thanks for noting it out :) @DonghyukJacobJang

**Comment by jxrin** [comment]
Added all the required fixes :) please let me know what you think! @DonghyukJacobJang

**Review by DonghyukJacobJang — COMMENTED** [review]
@jxrin Thanks for your fix. The idea was great!. However, I am afraid of approving this PR for now. There is an issue when locking and unlocking body scroll, it causes a page to be jumped x-axis due to appearing/disappearing native scroll bar on the right. 

Would you mind having a look at it?

**Comment by jxrin** [comment]
@DonghyukJacobJang yeah for sure! Could you give me a bit more information for what device and browser you noticed this behaviour on, and what your procedure is for testing? I can start debugging it then 😄

**Comment by DonghyukJacobJang** [comment]
@jxrin Please find an attached video as an issue reference.
I tested this on macOS 11 on Chrome 88.

https://user-images.githubusercontent.com/16929537/112197308-529fb480-8be2-11eb-9c9f-9c6cbd3c2822.mov

**Comment by jxrin** [comment]
Thanks for the video @DonghyukJacobJang :) I have some time today and tomorrow so I'll look into this and see what I can change

**Comment by KeshavChawla** [comment]
Hey @DonghyukJacobJang! I had some free time so I've been working on the generator. CC:: @jxrin 

I've been trying to reproduce the issue you mentioned in the video but I am unable to do so in the default settings (see video) but am able to by forcing scroll bars to always appear. By any chance do you have always on scrollbars enabled (macOS System Preferences > General > Show Scroll Bars)?

I am able to reduce the jumping by hiding the scroll bar all together:

```
::-webkit-scrollbar {
  display: none;
}
```

Is this what you meant or would you rather have the scrollbars force visibility when locked? Thanks!


https://user-images.githubusercontent.com/21203253/113174554-7da88a80-9218-11eb-9f66-1702a1800c6a.mov

**Comment by DonghyukJacobJang** [comment]
@KeshavChawla thanks for debugging the issue. I am afraid of saying No regarding the scrollbar options. I am using the default which is "Automatic ...". And for the A11y purpose, setting the web scrollbar to be `display none` is not recommended.

**Comment by namniak** [comment]
I think we might need to cancel this PR. as the existing solution proofed to be well working as expected in new and old browsers with scroll + lock + page restoration functionality @DonghyukJacobJang 
I don't think there's any better solution out there tbh

**Comment by alemesa** [comment]
I'll close this @DonghyukJacobJang spent a bit of time this morning looking at solutions and they are not better than ours, like Vadim said this has been tested cross browsers and performs well

**Pull request closed without merging**
